# Generated by Django 5.0.1 on 2024-01-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_owner'),
        ('reviews', '0002_alter_review_inspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='reviews',
            field=models.ManyToManyField(related_name='places_reviews', to='reviews.review'),
        ),
    ]
