# Generated by Django 5.0.1 on 2024-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_likes'),
        ('reviews', '0003_remove_review_inspiration_remove_review_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='places_reviews', to='reviews.review'),
        ),
    ]
