# Generated by Django 5.0.1 on 2024-01-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0001_initial'),
        ('places', '0002_place_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='places',
            field=models.ManyToManyField(related_name='inspirations', to='places.place'),
        ),
    ]
