# Generated by Django 5.0.1 on 2024-01-13 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0005_alter_inspiration_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='likes',
            field=models.ManyToManyField(related_name='inspirations_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
