# Generated by Django 5.0.1 on 2024-01-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0006_alter_inspiration_likes'),
        ('reviews', '0002_alter_review_inspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', to='reviews.review'),
        ),
    ]
