# Generated by Django 5.0.1 on 2024-01-14 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0007_inspiration_reviews'),
        ('reviews', '0003_remove_review_inspiration_remove_review_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='inspirations_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='reviews.review'),
        ),
    ]
