# Generated by Django 5.0.1 on 2024-01-13 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspirations', '0005_alter_inspiration_likes'),
        ('places', '0003_place_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration', to='inspirations.inspiration')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_reviews', to=settings.AUTH_USER_MODEL)),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.place')),
            ],
        ),
    ]
