# Generated by Django 5.0.1 on 2024-01-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0006_alter_inspiration_likes'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='inspiration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations', to='inspirations.inspiration'),
        ),
    ]
