# Generated by Django 5.0.1 on 2024-01-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_inspiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='inspiration',
        ),
        migrations.RemoveField(
            model_name='review',
            name='places',
        ),
    ]
