# Generated by Django 5.0.1 on 2024-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
