# Generated by Django 5.0.1 on 2024-01-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_image'),
        ('places', '0006_alter_place_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='boards', to='places.place'),
        ),
    ]
